collections:
  - name: 'otherPages'
    label: 'Other Pages'
    folder: 'src/data/otherPages'
    extension: mdx
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: settings
    label: 'Settings'
    files:
      - name: nav
        label: 'Nav'
        file: src/config/navData.json
        fields:
          - label: 'Nav'
            name: 'nav'
            widget: 'list'
            types:
              - label: 'Dropdown'
                name: dropdown
                widget: object
                fields:
                  - { label: 'Text', name: 'text', widget: 'string' }
                  - label: 'Dropdown'
                    name: dropdown
                    widget: list
                    fields:
                      - { label: 'Text', name: 'text', widget: 'string' }
                      - { label: 'Link', name: 'link', widget: 'string' }
              - label: 'Link'
                name: link
                widget: object
                fields:
                  - { label: 'Text', name: 'text', widget: 'string' }
                  - { label: 'Link', name: 'link', widget: 'string' }
      - name: siteData
        label: 'Site Data'
        file: src/config/siteData.json
        fields:
          - label: 'Name'
            name: name
            widget: string
          - label: 'Title'
            name: title
            widget: string
          - label: 'Description'
            name: description
            widget: markdown
          - label: 'Author'
            name: author
            widget: object
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
          - label: 'Default Image'
            name: defaultImage
            widget: object
            fields:
              - { label: 'Src', name: 'src', widget: 'image' }
              - { label: 'Alt', name: 'alt', widget: 'string' }
          - label: 'Register Link'
            name: registerLink
            widget: string
          - label: 'Contact'
            name: contact
            widget: object
            fields:
              - label: 'Name'
                name: name
                widget: string
              - label: 'Email'
                name: email
                widget: string
              - label: 'Phone'
                name: phone
                widget: string
          - label: 'Socials'
            name: socials
            widget: object
            fields:
              - label: 'Facebook'
                name: facebook
                widget: string
                required: false
              - label: 'Twitter'
                name: twitter
                widget: string
                required: false
              - label: 'Instagram'
                name: instagram
                widget: string
                required: false
              - label: 'Youtube'
                name: youtube
                widget: string
                required: false
      - name: hero
        label: 'Hero'
        file: src/data/staticSections/hero.mdx
        fields:
          - label: 'Title'
            name: title
            widget: string
          - label: 'Description'
            name: description
            widget: string
      - name: classInfo
        label: 'Class Info'
        file: src/data/staticSections/class-info.mdx
        fields:
          - label: 'Title'
            name: title
            widget: string
          - label: 'Content'
            name: body
            widget: markdown
      - name: contact
        label: 'Contact'
        file: src/data/staticSections/contact.mdx
        fields:
          - label: 'Image'
            name: image
            widget: image
            required: false
      - name: about
        label: 'About'
        file: src/data/staticSections/about.mdx
        fields:
          - label: 'Title'
            name: title
            widget: string
          - label: 'Name'
            name: name
            widget: string
          - label: 'Image'
            name: image
            widget: image
          - label: 'Quote Author'
            name: quoteAuthor
            widget: string
          - label: 'Content'
            name: body
            widget: markdown
media_folder: 'src/assets/images' # Location where files will be stored in the repo
public_folder: '@assets/images' # The src attribute for uploaded media
backend:
  name: github
  repo: eventistca/site-ncdance.ca
  base_url: https://sveltia-cms-auth.tiedye1.workers.dev/
